# Generated by Django 2.0.6 on 2018-07-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180724_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=12)),
                ('price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('descont', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=5, max_digits=5)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Person')),
            ],
        ),
    ]
