# Generated by Django 2.0.6 on 2018-07-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20180724_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='number',
        ),
        migrations.AddField(
            model_name='produto',
            name='description',
            field=models.CharField(default=None, max_length=27),
        ),
    ]
